name: Lint, Build, Test and Publish

on:
  push:
    branches:
      - main
    pull_request:


jobs:
  build:
    name: Installing & Building
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Cancel previous running workflows
        uses: fkirc/skip-duplicate-actions@master
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: yarn 
      - name: Lint, Test & Build
        run: npx nx affected -t lint test build
      - uses: actions/cache/save@v3
        with:
          path: packages/*/dist
          key: ${{ runner.os }}-build-${{ github.sha }}